export enum Syllable {
    a = "a",
    u = "u",
    e = "e",
    i = "i",
    tu = "tu",
    ti = "ti",
    ta = "ta",
    ni = "ni",
    nu = "nu",
    na = "na",
    ri = "ri",
    ru = "ru",
    ra = "ra",
    re = "re",
    mi = "mi",
    mu = "mu",
    ma = "ma",
    me = "me",
    la = "la",
    lu = "lu",
    li = "li",
    le = "le",
    hi = "hi",
    ha = "ha",
    hu = "hu",
    he = "he",
    de = "de",
    da = "da",
    du = "du",
    di = "di",
    ka = "ka",
    ki = "ki",
    ku = "ku",
    ke = "ke",
    za = "za",
    zi = "zi",
    zu = "zu",
    ze = "ze",
    ga = "ga",
    gi = "gi",
    gu = "gu",
    ge = "ge",
    fa = "fa",
    fi = "fi",
    fu = "fu",
    fe = "fe",
    sa = "sa",
    si = "si",
    su = "su",
    se = "se",
    ba = "ba",
    bi = "bi",
    bu = "bu",
    be = "be",
    vu = "vu",
    vi = "vi",
    va = "va",
    ve = "ve",
    consonant = "consonant",
}

export interface SyllableObject {
    syllable: Syllable;
    character: string;
}
